heat_template_version: 2013-05-23

description: >
  HOT template to test OS::Heat::APIC

resources:
  apic:
    type: OS::Heat::APIC
    properties:
      ToolkitMethod: Tenant
      ToolkitData: ByronDelete

  apic2:
    type: OS::Heat::APIC
    properties:
      ToolkitMethod: raw
      RawJSON: [ '/api/mo/uni.json' ,
      {"fvTenant":{"attributes":{"descr":"","dn":"uni/tn-Byron2","name":"Byron2"}}} ]


outputs:

  Name:
    description: Object Name
    value: { get_attr: [ apic, Name ] }
  Response:
    description: DN Object
    value: { get_attr: [ apic, Response ] }
  AuthStatusCode:
    description: Status of APIC Authentication
    value: { get_attr: [ apic, AuthStatusCode ] }
  Name2:
    description: Object Name
    value: { get_attr: [ apic2, Name ] }
  Response2:
    description: DN Object
    value: { get_attr: [ apic2, Response ] }
  AuthStatusCode2:
    description: Status of APIC Authentication
    value: { get_attr: [ apic2, AuthStatusCode ] }

